[build-system]
requires = ["setuptools>=84.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "TwinCons"
version = "0.7.0.dev0"
description = "TwinCons script for analysis of MSAs comprised of two sequence groups."
readme = "README_twc.md"
requires-python = ">=3.14"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Petar Penev", email = "ppenev@gatech.edu" },
]
urls = { Homepage = "https://github.com/petaripenev/AlignmentScore" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "biopython>=1.88",
]

[project.scripts]
twcons = "twincons.entry:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["twincons", "twincons.*"]

[tool.setuptools.package-data]
"twincons" = [
    "matrices/*.dat",
    "matrices/BLOSUM/*.out",
    "matrices/structureDerived/*.dat",
    "matrices/jp/*.dat",
]
